const messages=document.getElementById("messages"),welcome=document.getElementById("welcome"),input=document.getElementById("messageInput"),sendBtn=document.getElementById("sendBtn");let conversation=[];
async function sendMessage(customMessage=null){const text=customMessage||input.value.trim();if(!text||sendBtn.disabled)return;welcome.style.display="none";addMessage("user",text);input.value="";autoResize();conversation.push({role:"user",content:text});sendBtn.disabled=true;const id=showTyping();try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:conversation})});if(!r.ok)throw new Error("Server error");const d=await r.json(),reply=d.reply||"Sorry, I couldn't generate a response.";removeTyping(id);conversation.push({role:"assistant",content:reply});addMessage("assistant",reply)}catch(e){removeTyping(id);addMessage("assistant","⚠️ I couldn't connect to the AI server. Check that the backend is running and your API key is configured.")}finally{sendBtn.disabled=false;input.focus()}}
function addMessage(role,text){const m=document.createElement("div");m.className=`message ${role}`;m.innerHTML=`<div class="avatar">${role==="user"?"YOU":"TR"}</div><div class="message-body"><div class="message-name">${role==="user"?"You":"Tech Repeated Guide"}</div><div class="message-text">${formatMessage(text)}</div></div>`;messages.appendChild(m);scrollToBottom();addCopyEvents()}
function formatMessage(text){let e=escapeHTML(text);e=e.replace(/```(\w+)?\n?([\s\S]*?)```/g,(_,l,c)=>`<div class="code-block"><div class="code-header"><span>${l||"code"}</span><button class="copy-code">Copy</button></div><pre><code>${c.trim()}</code></pre></div>`);e=e.replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>");e=e.replace(/`([^`]+)`/g,"<code>$1</code>");return e}
function escapeHTML(t){const d=document.createElement("div");d.textContent=t;return d.innerHTML}
function addCopyEvents(){document.querySelectorAll(".copy-code").forEach(b=>{if(b.dataset.ready)return;b.dataset.ready="true";b.addEventListener("click",async()=>{const c=b.closest(".code-block").querySelector("code").innerText;try{await navigator.clipboard.writeText(c);b.textContent="Copied!";setTimeout(()=>b.textContent="Copy",1500)}catch{b.textContent="Failed"}})})}
function showTyping(){const id="typing-"+Date.now(),e=document.createElement("div");e.className="message assistant";e.id=id;e.innerHTML=`<div class="avatar">TR</div><div class="message-body"><div class="message-name">Tech Repeated Guide</div><div class="message-text"><div class="typing"><span></span><span></span><span></span></div></div></div>`;messages.appendChild(e);scrollToBottom();return id}
function removeTyping(id){document.getElementById(id)?.remove()}function scrollToBottom(){setTimeout(()=>document.getElementById("chatArea").scrollTop=document.getElementById("chatArea").scrollHeight,50)}function autoResize(){input.style.height="auto";input.style.height=Math.min(input.scrollHeight,140)+"px"}input.addEventListener("input",autoResize);input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});sendBtn.addEventListener("click",()=>sendMessage());
document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>sendMessage(b.dataset.prompt)));
function newChat(){conversation=[];messages.innerHTML="";welcome.style.display="block";input.value="";autoResize();input.focus()}document.getElementById("newChat").onclick=newChat;document.getElementById("newChatTop").onclick=newChat;document.getElementById("clearChat").onclick=newChat;
if(localStorage.getItem("trg-theme")==="dark")document.body.classList.add("dark");document.getElementById("themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("trg-theme",document.body.classList.contains("dark")?"dark":"light")};document.getElementById("mobileMenu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");